### ISSUE TITLE
Change parent particle inheritance on resampled particles

### ISSUE THREAD

**Issue by RajivPerera-Robotics** [a-matsoukas/robot_localization#10]
Create a lambda function that calculates characteristics for reseeded particles based on the characteristics of the seed particle. 

The function would be located within the Particle() class during initialization. It would take the parent cartesian variation, theta variation, and particle weight and input it into a function that returns the child particle variations.

The purpose of this being a lambda function is that we can have multiple functions that calculate this differently, and directly compare their effects by hot swapping out what's in the lambda function. This could also probably be done without a lambda function, if it's clean. 

Examples of different child functions: one that increases/decreases variation linearly based on the weight of a particle, one that makes either cartesian or theta variation zero randomly, other stuff idk

[https://miro.medium.com/v2/resize:fit:828/format:webp/1*QXqq-wElxkqjBZ_e-HI2kw.png](url) <- I always forget how lambda functions work

**Comment by a-matsoukas** [comment]
I implemented this a little differently than described here. Happy to move stuff around, but the functions are in the PF node's resample_particles method, and the resampled particles are passed their calculated softmaxes instead of the lambda function.

I implemented this using an exponential curve, where the closer the seed weight is to the its max possible value, the smaller the softmax is. The math probably looks weird in code, so I am happy to explain the choices behind it at our next meeting.
